import Head from "next/head"
import Image from "next/image"
import { Header } from "@/components/Header"
import { readFile } from "fs/promises"

export default function Comic({ id, img, alt, title, width, heigth }){
  return(
    <>
      <Head>
        <title>xkcd - Comics for developers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />

      <main>

      </main>
    </>
  )
}

export async function getStaticPaths(){
  return{
    paths: [
      { params: { id: '2500' } }, 
    ],
    fallback: false,
  }

}

export async function getStaticPorps({ params }){
  const { id } = params

  const content = await readFile(`./comics/${id}.json`, "utf-8")
  const comic = JSON.parse(content)

  return {
    props: {
     ...comic
    }
  }


}